version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
